// Public-page-only diagnostic. No application source, credentials or environment output.
import fs from 'node:fs';
import {createRequire} from 'node:module';
const req=createRequire(process.argv[2]+'/package.json');
const {chromium}=req('playwright');
const pixelmatch=req('pixelmatch').default;const {PNG}=req('pngjs');
const root='https://cfd1cff7-vigia-runtime.c-gamiz93.workers.dev';
const out='chromium-evidence';fs.mkdirSync(out,{recursive:true});
const report={candidate:'738a798a3a8eddc285efd69fad78678da085f08c',preview:root,execution:'Chromium on Linux; mobile/tablet emulation, no Android or Windows claim',cases:[],screenshots:[],f7:[]};
const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});report.browser=browser.version();
const persist=()=>fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));
async function test(name,fn){try{report.cases.push({case:name,status:'PASS',evidence:await fn()});}catch(e){report.cases.push({case:name,status:'FAIL',error:String(e).slice(0,1800)});}persist();}
async function ready(p){await p.waitForSelector('#terminal-results-title');await p.waitForFunction(()=>document.querySelector('.na-terminal-results')?.getAttribute('aria-busy')==='false');}
async function shot(p,name){await p.screenshot({path:out+'/'+name+'.png',fullPage:false});report.screenshots.push(name+'.png');}
async function geom(p){return p.evaluate(()=>{const b=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};const a=document.querySelector('.na-public-brand');const text=[];for(const e of a.querySelectorAll('.na-brand-name,small')){const r=document.createRange();r.selectNodeContents(e);text.push(...Array.from(r.getClientRects(),x=>({x:x.x,y:x.y,right:x.right,bottom:x.bottom})));}const controls=Array.from(document.querySelectorAll('.na-public-header__actions a,.na-public-header__actions summary,.na-theme-toggle')).filter(e=>e.getBoundingClientRect().height&&e.checkVisibility({visibilityProperty:true,opacityProperty:true})).map(e=>{const r=b(e);return {box:r,text:e.textContent,hit:[.2,.5,.8].every(t=>e.contains(document.elementFromPoint(r.x+r.width*t,r.y+r.height/2)))}});return {brand:b(a),text,controls,width:innerWidth,documentWidth:document.documentElement.scrollWidth};});}
function checkGeom(g){const overlap=(a,b)=>Math.min(a.right,b.right)>Math.max(a.x,b.x)+1&&Math.min(a.bottom,b.bottom)>Math.max(a.y,b.y)+1;for(const t of g.text){if(t.x<g.brand.x-1||t.right>g.brand.right+1)throw Error('Brand paint outside its link '+JSON.stringify(g));if(g.controls.some(c=>overlap(t,c.box)))throw Error('Brand/control collision '+JSON.stringify(g));}if(g.controls.some(c=>!c.hit))throw Error('Obstructed click area '+JSON.stringify(g));if(g.documentWidth>g.width+1)throw Error('Document overflow');}
try {
for(const [name,width,height,mobile,dpr] of [['mobile',393,852,true,3],['desktop',1363,936,false,1],['tablet',820,1180,true,2],['narrow',320,700,true,2]]){
 const ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:dpr,isMobile:mobile,hasTouch:mobile,colorScheme:'light'});const p=await ctx.newPage();p.setDefaultTimeout(10000);
 await p.goto(root+'/es/alertas');await ready(p);
 await test(name+'-consent-reject',async()=>{await p.getByRole('button',{name:'Rechazar analítica',exact:true}).click();await p.reload();await ready(p);if(await p.locator('[role=dialog]').count())throw Error('Consent not persistent');return p.evaluate(()=>JSON.parse(localStorage.getItem('nagamealert.analytics-consent.v1')));});
 await test(name+'-geometry',async()=>{await shot(p,name+'-header');const g=await geom(p);checkGeom(g);return g;});
 if(name==='mobile'){
 await test('system-theme-real-media-change',async()=>{await ctx.clearCookies();await p.evaluate(()=>localStorage.removeItem('nagamealert-theme'));await p.reload();for(const appearance of ['dark','light']){await p.emulateMedia({colorScheme:appearance});await p.waitForFunction(v=>document.documentElement.getAttribute('data-na-theme')===v,appearance);}return {darkLightMediaChanges:true,emulatedSystemPreference:true};});
 await test('manual-theme-persistence-precedence',async()=>{await p.locator('.na-theme-toggle').click();await p.reload();await p.emulateMedia({colorScheme:'dark'});await p.emulateMedia({colorScheme:'light'});await p.waitForFunction(()=>document.documentElement.getAttribute('data-na-theme')==='dark');await shot(p,'mobile-dark');return {stored:await p.evaluate(()=>localStorage.getItem('nagamealert-theme'))};});
 await test('invalid-theme',async()=>{await p.evaluate(()=>localStorage.setItem('nagamealert-theme','invalid'));await p.reload();await p.waitForFunction(()=>document.documentElement.getAttribute('data-na-theme')==='light');return {fallback:'light'};});
 await test('consent-accept-preview-contract',async()=>{await p.evaluate(()=>localStorage.removeItem('nagamealert.analytics-consent.v1'));await p.reload();await p.getByRole('button',{name:'Aceptar analítica',exact:true}).click();await p.reload();await ready(p);const x=await p.evaluate(()=>({consent:JSON.parse(localStorage.getItem('nagamealert.analytics-consent.v1')),ga:!!document.querySelector('script[src*=googletagmanager]')}));if(x.consent.choice!=='accepted'||x.ga)throw Error(JSON.stringify(x));return x;});
 await test('mobile-menu',async()=>{await p.locator('.na-public-mobile-nav summary').click();if(!await p.locator('.na-public-mobile-nav a').first().isVisible())throw Error('Links hidden');await shot(p,'mobile-menu');const panel=await p.locator('.na-public-nav--mobile').boundingBox();if(panel.x<0||panel.x+panel.width>393)throw Error('Menu panel clipped '+JSON.stringify(panel));await p.locator('.na-public-mobile-nav summary').click();return {openedClosed:true};});
 await test('filters-apply-clear-focus-scroll',async()=>{await p.locator('.na-terminal-filter-trigger').click();await p.locator('#terminal-country').selectOption('ES');await p.waitForURL(/country=ES/);await ready(p);await shot(p,'mobile-filters');await p.getByRole('button',{name:'Restablecer filtros',exact:true}).click();await p.waitForFunction(()=>!new URL(location.href).searchParams.has('country'));await p.getByRole('button',{name:'Ver resultados',exact:true}).click();await p.waitForFunction(()=>document.activeElement?.classList.contains('na-terminal-filter-trigger'));return {countryCleared:true,focusReturned:true};});
 await test('search-input-keyboard-focus-results',async()=>{await p.locator('#global-alert-search').fill('cacahuete');await p.locator('#global-alert-search').press('Enter');await p.waitForURL(/q=cacahuete/);await ready(p);if(!/cacahuete/i.test(await p.locator('.na-terminal-results').innerText()))throw Error('Expected result absent');await shot(p,'mobile-search');return {query:'cacahuete',resultContent:true,keyboard:'automated DOM key, no native software keyboard claim'};});
 await test('map-detail-return',async()=>{await p.goto(root+'/es/alertas?source=AESAN');await ready(p);await p.locator('.na-terminal-map').waitFor();await shot(p,'mobile-map');const link=p.locator('.na-terminal-results a[href*="/alerta/"]').filter({hasText:/cacahuete/i}).first();await link.click();await p.waitForURL(/\/alerta\//);const h=await p.locator('h1').innerText();if(!/cacahuete/i.test(h))throw Error('Wrong detail');await shot(p,'mobile-detail');await p.goBack();await ready(p);return {detail:h,backToResults:true};});
 await test('orientation-emulated-geometry',async()=>{await p.goto(root+'/es/alertas');await ready(p);await p.setViewportSize({width:852,height:393});const g=await geom(p);checkGeom(g);await shot(p,'mobile-landscape');await p.setViewportSize({width,height});return {...g,orientation:'viewport emulation'};});
 }
 // F7 compare under same engine, viewport, DPR, fonts, storage and fixed animation phase.
 await test(name+'-F7-approved-production-comparison',async()=>{const states=[];for(const [label,url] of [['baseline','https://nagamealert.com/es/'],['candidate',root+'/es/']]){await p.goto(url);await p.evaluate(async()=>{await document.fonts.ready;localStorage.setItem('nagamealert-theme','light');localStorage.setItem('nagamealert.analytics-consent.v1',JSON.stringify({choice:'rejected',updatedAt:1,version:1}));for(const a of document.getAnimations()){a.pause();a.currentTime=0;}});await p.reload();await p.evaluate(async()=>{await document.fonts.ready;for(const a of document.getAnimations()){a.pause();a.currentTime=0;}});await p.waitForTimeout(300);const state=await p.evaluate(()=>({url:location.href,viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,scale:visualViewport.scale,fonts:document.fonts.status,theme:document.documentElement.getAttribute('data-na-theme')}));states.push(state);await shot(p,name+'-f7-'+label);}
 const a=PNG.sync.read(fs.readFileSync(out+'/'+name+'-f7-baseline.png')),b=PNG.sync.read(fs.readFileSync(out+'/'+name+'-f7-candidate.png'));if(a.width!==b.width||a.height!==b.height)throw Error('Different dimensions');const diff=new PNG({width:a.width,height:a.height});const pixels=pixelmatch(a.data,b.data,diff.data,a.width,a.height,{threshold:0,includeAA:true});fs.writeFileSync(out+'/'+name+'-f7-diff.png',PNG.sync.write(diff));report.screenshots.push(name+'-f7-diff.png');const x={viewport:name,states,changedPixels:pixels,totalPixels:a.width*a.height};report.f7.push(x);if(pixels||states[0].theme!==states[1].theme)throw Error(JSON.stringify(x));return x;});
 await ctx.close();
}
}finally{await browser.close();persist();}
