// One bounded repetition of two failed public-page checks; no app source or secrets.
import fs from 'node:fs';import{createRequire}from'node:module';
const req=createRequire(process.argv[2]+'/package.json'),{chromium}=req('playwright'),{PNG}=req('pngjs'),pixelmatch=req('pixelmatch').default;
const root='https://8c4df878-vigia-runtime.c-gamiz93.workers.dev',out='two-case-evidence';fs.mkdirSync(out,{recursive:true});
const report={candidate:'df5ea1f2918ae232c22e7a31bb0866ab910eb881',preview:root,cases:[],screenshots:[]};
const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});report.browser=browser.version();
const persist=()=>fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));
async function test(name,fn){try{report.cases.push({case:name,status:'PASS',evidence:await fn()});}catch(e){report.cases.push({case:name,status:'FAIL',error:String(e).slice(0,2000)});}persist();}
async function ready(p){await p.waitForFunction(()=>document.querySelector('.na-terminal-results')?.getAttribute('aria-busy')==='false');}
try{
 await test('system-theme-after-client-ready',async()=>{const ctx=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:3,isMobile:true,hasTouch:true,colorScheme:'light'});const p=await ctx.newPage();p.setDefaultTimeout(10000);await p.goto(root+'/es/alertas');await p.getByRole('button',{name:'Rechazar analítica',exact:true}).click();await ready(p);await p.evaluate(()=>localStorage.removeItem('nagamealert-theme'));await p.reload();await ready(p);const states=[];for(const mode of ['dark','light']){await p.emulateMedia({colorScheme:mode});await p.waitForFunction(v=>document.documentElement.getAttribute('data-na-theme')===v,mode);const s=await p.evaluate(()=>({theme:document.documentElement.getAttribute('data-na-theme'),stored:localStorage.getItem('nagamealert-theme'),prefersDark:matchMedia('(prefers-color-scheme: dark)').matches}));if(s.stored!==null)throw Error('Manual override present');states.push(s);await p.screenshot({path:out+'/system-'+mode+'.png'});report.screenshots.push('system-'+mode+'.png');}await ctx.close();return {states,execution:'Chromium mobile emulation; actual matchMedia change, no direct theme-attribute mutation'};});
 await test('F7-desktop-fixed-animation-phase',async()=>{const ctx=await browser.newContext({viewport:{width:1363,height:936},deviceScaleFactor:1,colorScheme:'light'});const p=await ctx.newPage();p.setDefaultTimeout(10000);const states=[];for(const[label,url]of[['baseline','https://nagamealert.com/es/'],['candidate',root+'/es/']]){await p.goto(url);await p.evaluate(()=>{localStorage.setItem('nagamealert-theme','light');localStorage.setItem('nagamealert.analytics-consent.v1',JSON.stringify({choice:'rejected',updatedAt:Date.now(),version:1}));});await p.reload();await p.waitForFunction(()=>!document.querySelector('[role=dialog]')&&document.fonts.status==='loaded'&&Array.from(document.images).every(i=>i.complete));await p.waitForTimeout(800);await p.evaluate(()=>{for(const a of document.getAnimations()){a.pause();a.currentTime=0;}});await p.waitForTimeout(400);const state=await p.evaluate(()=>({url:location.href,viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,scale:visualViewport.scale,theme:document.documentElement.getAttribute('data-na-theme'),fonts:document.fonts.status,consent:JSON.parse(localStorage.getItem('nagamealert.analytics-consent.v1'))?.choice,animations:document.getAnimations().map(a=>({name:a.animationName,time:a.currentTime,state:a.playState}))}));states.push(state);await p.screenshot({path:out+'/f7-desktop-'+label+'.png'});report.screenshots.push('f7-desktop-'+label+'.png');}const a=PNG.sync.read(fs.readFileSync(out+'/f7-desktop-baseline.png')),b=PNG.sync.read(fs.readFileSync(out+'/f7-desktop-candidate.png')),diff=new PNG({width:a.width,height:a.height});const pixels=pixelmatch(a.data,b.data,diff.data,a.width,a.height,{threshold:0,includeAA:true});fs.writeFileSync(out+'/f7-desktop-diff.png',PNG.sync.write(diff));report.screenshots.push('f7-desktop-diff.png');report.f7={states,changedPixels:pixels,totalPixels:a.width*a.height};await ctx.close();if(pixels)throw Error(JSON.stringify(report.f7));return report.f7;});
}finally{await browser.close();persist();}
